package com.pms.rules.workflow.cc

import com.pms.drools.domain.WorkflowCcBean;

/*
* 考勤审批-加班-抄送规则
*/
rule "attendance_overtime_cc_drools_1"
    no-loop true
    lock-on-active true
    salience 300
    when
        $workflowCc : WorkflowCcBean(businessType == "attendance_overtime" && (account == "yuanxingyu" || account == "wuxiaoming" || account == "shenqi" || account == "wengguohai" || account == "yaoxianyou" || account == "mayingchun" || account == "zhengchengbin"))
    then
        System.out.println("attendance_overtime_cc_drools_1 命中");
        $workflowCc.setCcAccounts("wengguohai,huajianhe");
end

rule "attendance_overtime_cc_drools_2"
    no-loop true
    lock-on-active true
    salience 0
    when
        $workflowCc : WorkflowCcBean(businessType == "attendance_overtime"  && (account != "yuanxingyu" && account != "wuxiaoming" && account != "shenqi" && account != "wengguohai" && account != "yaoxianyou" && account != "mayingchun" && account != "zhengchengbin"))
    then
        System.out.println("attendance_overtime_cc_drools_2 命中");
        $workflowCc.setCcRoleCodes("pm,pd,dm");
end
